---
- name: Preparar Servidor Ubuntu para a Web API .NET
  hosts: all
  become: yes # Executar como root (sudo)
  vars:
    app_dir: /var/www/ExemploDevOps
    app_dll: ExemploDevOps.Api.dll

  tasks:
    - name: Atualizar o cache do APT
      apt:
        update_cache: yes

    - name: Instalar o ASP.NET Core Runtime 8.0
      apt:
        name: aspnetcore-runtime-8.0
        state: present

    - name: Criar a pasta da aplicacao
      file:
        path: "{{ app_dir }}"
        state: directory
        # Mudamos o dono para 'ubuntu' para que o Jenkins consiga enviar arquivos via SCP depois sem erro de permissao
        owner: ubuntu 
        group: ubuntu
        mode: '0775'

    - name: Criar o servico Systemd (Pronto para quando o Jenkins enviar a API)
      copy:
        dest: /etc/systemd/system/webapi.service
        content: |
          [Unit]
          Description=Web API .NET
          
          [Service]
          WorkingDirectory={{ app_dir }}
          ExecStart=/usr/bin/dotnet {{ app_dir }}/{{ app_dll }}
          Restart=always
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=webapi-dotnet
          User=ubuntu
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=ASPNETCORE_URLS=http://*:5000

          [Install]
          WantedBy=multi-user.target

    - name: Recarregar o Systemd e habilitar o servico
      systemd:
        name: webapi.service
        enabled: yes
        daemon_reload: yes
        # Retiramos o 'state: restarted' porque a API ainda nao foi enviada pelo Jenkins.
        # Quem vai dar o comando de start/restart sera o proprio Jenkins!
