name: Build and Push Docker Image

on:
  # Escolha o gatilho:
  push:
    branches: [ "aula06-infisical-ga" ] # Roda quando você der push na main
  workflow_dispatch:
  
permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for checking out code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: "oidc"
          identity-id: "a3d97c6d-2bd6-4790-86cb-8f1562cde64e"  # From Step 4
          project-slug: "aula03-4-aak"      # Your Infisical project slug
          env-slug: "dev"                        # Your environment slug

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/calculadora:latest
          build-args: |
            data1=${{ env.data1 }}
            data2=${{ env.data2 }}
          
  deploy:
    runs-on: aws
    needs: [build]
    steps:
      - name: Run and Print Logs
        run: |
          docker run -d --name calculadora-app -p 5001:8080 wellisonraul/calculadora:latest
          sleep 10
    
          echo "--- LOGS DO CONTAINER ---"
          docker logs calculadora-app
          
          docker ps -a | grep calculadora-app
          
          docker rm -f calculadora-app
